# Generated by Django 2.1.7 on 2019-03-31 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='code',
            field=models.IntegerField(verbose_name='Diagnosis Code'),
        ),
    ]
