# Generated by Django 2.1.7 on 2019-03-31 07:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0002_auto_20190331_0729'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created On'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated On'),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created On'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='description',
            field=models.CharField(default=2, max_length=70, verbose_name='Description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated On'),
        ),
    ]
