# Generated by Django 2.1.7 on 2019-03-31 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0003_auto_20190331_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='description',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Description'),
        ),
    ]
