# Generated by Django 2.1.7 on 2019-04-01 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0004_auto_20190331_0748'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='full_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Full Code'),
        ),
    ]
