# Generated by Django 2.1.7 on 2019-04-01 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0005_diagnosis_full_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='full_code',
            field=models.CharField(default=345, max_length=10, unique=True, verbose_name='Full Code'),
            preserve_default=False,
        ),
    ]
