# Generated by Django 2.2 on 2019-04-02 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0006_auto_20190401_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='code',
            field=models.CharField(max_length=6, unique=True, verbose_name='Category Code'),
        ),
    ]
