# Generated by Django 2.2 on 2019-04-03 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0007_changed_code_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='code',
            field=models.CharField(blank=True, max_length=7, verbose_name='Diagnosis Code'),
        ),
    ]
