# Generated by Django 2.2 on 2019-04-03 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0009_added_icd_type_to_dianosis_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Category Title'),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Description'),
        ),
    ]
